"use client";
import { FormEvent, useEffect, useState } from "react";
import { Check, FilePlus2, Printer, RefreshCw, Send } from "lucide-react";
import { WorkspaceNavigation } from "@/components/WorkspaceNavigation";
import { apiClient } from "@/lib/api-client";

type Customer={id:string;name:string}; type Product={id:string;name:string;sku:string;sellingPrice:number|string}; type Quote={id:string;quotationNumber?:string;status?:string;customer?:Customer;subtotal?:number|string;taxAmount?:number|string;totalAmount?:number|string};
const unwrap=(response:any)=>{const payload=response?.data?.data??response?.data??response;return payload?.data??payload??[]}; const money=(value:any)=>`TSh ${Number(value||0).toLocaleString()}`;
export default function QuotationsPage(){const [quotes,setQuotes]=useState<Quote[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[products,setProducts]=useState<Product[]>([]),[form,setForm]=useState({customerId:"",productId:"",quantity:"1",unitPrice:"0",discountPercent:"0"}),[error,setError]=useState(""),[message,setMessage]=useState("");
 async function load(){try{const [q,c,p]=await Promise.all([apiClient.get('/sales/quotations?page=1&limit=100'),apiClient.get('/customers?page=1&limit=100'),apiClient.get('/products?page=1&limit=100')]);setQuotes(unwrap(q));setCustomers(unwrap(c));setProducts(unwrap(p));}catch(e:any){setError(e?.response?.data?.message||'Quotations could not be loaded.')}} useEffect(()=>{void load()},[]);
 async function create(event:FormEvent){event.preventDefault();if(!form.customerId||!form.productId||Number(form.quantity)<=0||Number(form.unitPrice)<=0){setError('Customer, product, quantity, and price are required.');return}try{const created=unwrap(await apiClient.post('/sales/quotations',{customerId:form.customerId,discountPercent:Number(form.discountPercent),items:[{productId:form.productId,quantity:Number(form.quantity),unitPrice:Number(form.unitPrice)}]}));setMessage(`${created.quotationNumber} created with total ${money(created.totalAmount)}.`);setForm({...form,productId:'',quantity:'1',unitPrice:'0'});await load()}catch(e:any){setError(e?.response?.data?.message||'Quotation could not be created.')}}
 async function action(quote:Quote,path:string){try{const result=unwrap(await apiClient.patch(`/sales/quotations/${quote.id}/${path}`));setMessage(`${result.quotationNumber} is now ${result.status}.`);await load()}catch(e:any){setError(e?.response?.data?.message||'Quotation action failed.')}}
 async function convert(quote:Quote){try{const result=unwrap(await apiClient.post(`/sales/quotations/${quote.id}/convert-to-so`));setMessage(`${result.orderNumber} created from ${quote.quotationNumber}.`);await load()}catch(e:any){setError(e?.response?.data?.message||'Quotation conversion failed.')}}
 async function print(quote:Quote){const response=await apiClient.get(`/documents/quotations/${quote.id}/print-pdf`,{responseType:'blob'});const url=URL.createObjectURL(response.data);const link=document.createElement('a');link.href=url;link.download=`${quote.quotationNumber}.pdf`;link.click();URL.revokeObjectURL(url)}
 return <><WorkspaceNavigation/><main className="min-h-screen bg-background px-4 py-6 text-foreground sm:px-8"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-end justify-between gap-4 border-b border-border-default pb-6"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Sales control</p><h1 className="mt-2 text-4xl font-semibold">Quotations.</h1><p className="mt-2 text-sm text-foreground/55">Price, send, accept, and convert customer quotations.</p></div><button onClick={()=>void load()} className="flex items-center gap-2 border px-4 py-2 text-xs font-semibold uppercase"><RefreshCw size={15}/> Refresh</button></header>{error&&<p role="alert" className="mt-5 border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message&&<p role="status" className="mt-5 border border-green-200 bg-green-50 p-3 text-sm text-green-700">{message}</p>}
 <form onSubmit={create} className="mt-7 grid gap-3 bg-primary p-5 text-white sm:grid-cols-2 lg:grid-cols-6"><select aria-label="Quotation customer" value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})} className="h-11 border border-border-default bg-card px-3 text-sm text-foreground"><option value="">Customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="Quotation product" value={form.productId} onChange={e=>{const p=products.find(x=>x.id===e.target.value);setForm({...form,productId:e.target.value,unitPrice:p?String(p.sellingPrice):form.unitPrice})}} className="h-11 border border-border-default bg-card px-3 text-sm text-foreground"><option value="">Product</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} · {p.name}</option>)}</select><input aria-label="Quotation quantity" type="number" min=".01" step=".01" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})} className="h-11 border border-border-default bg-card px-3 text-foreground placeholder:text-foreground/45" placeholder="Qty"/><input aria-label="Quotation unit price" type="number" min=".01" step=".01" value={form.unitPrice} onChange={e=>setForm({...form,unitPrice:e.target.value})} className="h-11 border border-border-default bg-card px-3 text-foreground placeholder:text-foreground/45" placeholder="Price"/><input aria-label="Quotation discount" type="number" min="0" step=".01" value={form.discountPercent} onChange={e=>setForm({...form,discountPercent:e.target.value})} className="h-11 border border-border-default bg-card px-3 text-foreground placeholder:text-foreground/45" placeholder="Discount %"/><button className="flex items-center justify-center gap-2 bg-card px-4 text-xs font-semibold uppercase text-foreground"><FilePlus2 size={15}/> Save draft</button></form>
 <section className="mt-8 space-y-3"><h2 className="text-xl font-semibold">Quotation register</h2>{quotes.map(q=><article key={q.id} className="flex flex-col gap-4 bg-card p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{q.quotationNumber}</p><p className="mt-1 text-xs uppercase tracking-[.1em] text-foreground/50">{q.status} · {q.customer?.name} · {money(q.totalAmount)}</p></div><div className="flex flex-wrap gap-2">{q.status==='DRAFT'&&<button onClick={()=>void action(q,'send')} className="flex items-center gap-2 bg-primary px-3 py-2 text-xs font-semibold uppercase text-white"><Send size={14}/> Send</button>}{q.status==='SENT'&&<button onClick={()=>void action(q,'accept')} className="flex items-center gap-2 border px-3 py-2 text-xs font-semibold uppercase"><Check size={14}/> Accept</button>}{(q.status==='ACCEPTED'||q.status==='DRAFT')&&<button onClick={()=>void convert(q)} className="border px-3 py-2 text-xs font-semibold uppercase">Convert SO</button>}<button onClick={()=>void print(q)} className="flex items-center gap-2 border px-3 py-2 text-xs font-semibold uppercase"><Printer size={14}/> Print</button></div></article>)}</section></div></main></>}
